### ISSUE TITLE
Add more tests for functions that can take different number of args

### ISSUE THREAD

**Issue by elenam** [Clojure-Intro-Course/babel#15]
`take` is well-tested, but we need more tests for `reduce`, `map`, etc. - both tests that shouldn't produce errors and those that do.

**Comment by stanislowskij** [comment]
This commit was transferred from the [legacy repository](https://github.com/Clojure-Intro-Course/babel-legacy) as part of our Fall 2024 housekeeping effort. The issue has been removed from the legacy repository.
