### ISSUE TITLE
Refactor logging so that log files are consistent with html

### ISSUE THREAD

**Issue by elenam** [Clojure-Intro-Course/babel#20]
Currently there are two different data formattings: one for html, one for logs. Need to separate them out into a function to make them consistent.

**Comment by stanislowskij** [comment]
This commit was transferred from the [legacy repository](https://github.com/Clojure-Intro-Course/babel-legacy) as part of our Fall 2024 housekeeping effort. The issue has been removed from the legacy repository.

**Comment by stanislowskij** [comment]
We are only using HTML for logging.
