### ISSUE TITLE
Fix and refactor babel spec errors processing

### ISSUE THREAD

**Issue by elenam** [Clojure-Intro-Course/babel#21]
- [x] Fix the bug(s) in processing
- [x] Refactor the sequence of methods that process these errors
- [x] Move these methods to `utils.clj`
- [x] Make babel spec definitions in corefns consistent

**Comment by stanislowskij** [comment]
This commit was transferred from the [legacy repository](https://github.com/Clojure-Intro-Course/babel-legacy) as part of our Fall 2024 housekeeping effort. The issue has been removed from the legacy repository.

**Comment by stanislowskij** [comment]
Last part of this was done by https://github.com/Clojure-Intro-Course/babel/issues/59.
