### ISSUE TITLE
Add control for logging stacktrace

### ISSUE THREAD

**Issue by elenam** [Clojure-Intro-Course/babel#28]
Make stacktrace logging optional. One possibility would be to add a global atom to switch it on/off and an optional keyword to selectively record it.

**Comment by stanislowskij** [comment]
This commit was transferred from the [legacy repository](https://github.com/Clojure-Intro-Course/babel-legacy) as part of our Fall 2024 housekeeping effort. The issue has been removed from the legacy repository.

**Comment by stanislowskij** [comment]
Probably not necessary for now?
