### ISSUE TITLE
add spec for "require"

### ISSUE THREAD

**Issue by elenam** [Clojure-Intro-Course/babel#3]
The error on "require" is misleading:
```
utilities.spec_generator=> (require "nonsense")

Don't know how to create a sequence from a character.
```
Need to check what types are ok (note: this may be tricky!) and add a spec. 
There is also this case:
```
utilities.spec_generator=> (require [])

No value found for key true. Every key for a hash-map must be followed by a value.
```
We _may_ be able to approach it with spec, but need to be careful.

**Comment by stanislowskij** [comment]
This commit was transferred from the [legacy repository](https://github.com/Clojure-Intro-Course/babel-legacy) as part of our Fall 2024 housekeeping effort. The issue has been removed from the legacy repository.

**Comment by stanislowskij** [comment]
Subsumed by https://github.com/Clojure-Intro-Course/babel/issues/66
