### ISSUE TITLE
colorblind mode doesn't work for win10

### ISSUE THREAD

**Issue by plumstyle** [Clojure-Intro-Course/babel#4]
The color codes for colorblindness are in html_log.clj @ line 106 & 108.

**Comment by stanislowskij** [comment]
This commit was transferred from the [legacy repository](https://github.com/Clojure-Intro-Course/babel-legacy) as part of our Fall 2024 housekeeping effort. The issue has been removed from the legacy repository.

**Comment by stanislowskij** [comment]
As far as we can tell, logging and colorblind mode seem to be working in Windows 11. Windows 10 is outdated now.
