### ISSUE TITLE
misleading errors for select spec macro errors

### ISSUE THREAD

**Issue by holma198** [Clojure-Intro-Course/babel#5]
(if-some [[a b]] (+ a b) (+ b a))

Parameters for if-some must come in pairs, but b] does not have a match.

 -- this needs to be fixed for vector and keyword errors
(let [(b c) 4 a (inc 2)] (+ a b c))

utilities.spec_generator=> In let (b c) is used instead of a variable name.

(let [[b c] 4 a (inc 2)] (+ a b c))

Function nth does not allow a number as an argument.

**Comment by stanislowskij** [comment]
This commit was transferred from the [legacy repository](https://github.com/Clojure-Intro-Course/babel-legacy) as part of our Fall 2024 housekeeping effort. The issue has been removed from the legacy repository.

**Comment by stanislowskij** [comment]
First two cases are handled more appropriately now.

```clojure
(if-some [[a b]] (+ a b) (+ b a))
```
```
if-some requires exactly two elements in its vector, but a different number was given.
```

```clojure
(let [(b c) 4 a (inc 2)] (+ a b c))
```
```
Syntax problems with (let [(b c) 4 a (inc 2)] (+ a b c)):
In place of (b c) the following are allowed: a name or a vector or a hashmap
```

Last case is now a separate issue: https://github.com/Clojure-Intro-Course/babel/issues/67.
