### ISSUE TITLE
Output intermediate step in spec generation as a vector

### ISSUE THREAD

**Issue by EthanUphoff** [Clojure-Intro-Course/babel#6]
- [ ]  Put intermediate step to a file

- [ ] Make into vector with the format [name [vector of vector of args]]

- [ ] Make a function which slurps from a file the user specifies and outputs another file.

- [ ]  Document all of this.

**Comment by stanislowskij** [comment]
This commit was transferred from the [legacy repository](https://github.com/Clojure-Intro-Course/babel-legacy) as part of our Fall 2024 housekeeping effort. The issue has been removed from the legacy repository.

**Comment by stanislowskij** [comment]
We are not automatically generating specs in this project. This issue was more of an idea.
